-- Real Amazon Products Seed Data
-- Delete existing products
DELETE FROM product;

-- Reset auto increment
ALTER TABLE product AUTO_INCREMENT = 1;

-- Insert products with real Amazon images and USD prices
INSERT INTO product (name, brand, category, price, image, isActive, createdAt, updatedAt) VALUES
('Apple iPhone 15 Pro Max 256GB Natural Titanium', 'Apple', 'Electronics', 1199.00, 'https://m.media-amazon.com/images/I/81SigpJN1KL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Samsung Galaxy S24 Ultra 256GB Titanium Black', 'Samsung', 'Electronics', 1299.99, 'https://m.media-amazon.com/images/I/71lSiB0tQLL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Google Pixel 8 Pro 128GB Obsidian', 'Google', 'Electronics', 999.00, 'https://m.media-amazon.com/images/I/71f3hXNgTXL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('OnePlus 12 256GB Silky Black', 'OnePlus', 'Electronics', 799.99, 'https://m.media-amazon.com/images/I/71K96cE4URL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Apple MacBook Pro 14 M3 Pro 512GB Space Black', 'Apple', 'Laptop', 1999.00, 'https://m.media-amazon.com/images/I/61lsexTEJtL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Dell XPS 15 Intel Core i7 32GB 1TB SSD', 'Dell', 'Laptop', 1849.99, 'https://m.media-amazon.com/images/I/91MXLpouhoL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('ASUS ROG Zephyrus G14 RTX 4060 Gaming Laptop', 'ASUS', 'Laptop', 1599.99, 'https://m.media-amazon.com/images/I/81GrCeuCzxL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Lenovo ThinkPad X1 Carbon Gen 11 i7 16GB', 'Lenovo', 'Laptop', 1679.00, 'https://m.media-amazon.com/images/I/61QGMX0Qy6L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Apple iPad Pro 12.9 M2 256GB WiFi Space Gray', 'Apple', 'Tablet', 1099.00, 'https://m.media-amazon.com/images/I/81gC7frRJyL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Samsung Galaxy Tab S9 Ultra 256GB Graphite', 'Samsung', 'Tablet', 1199.99, 'https://m.media-amazon.com/images/I/81Wr3rMdfsL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Sony WH-1000XM5 Wireless Noise Canceling Headphones', 'Sony', 'Audio', 398.00, 'https://m.media-amazon.com/images/I/61vJtKbAssL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Apple AirPods Pro 2nd Generation with MagSafe', 'Apple', 'Audio', 249.00, 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Bose QuietComfort Ultra Headphones Black', 'Bose', 'Audio', 429.00, 'https://m.media-amazon.com/images/I/51QesHtV8gL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('JBL Flip 6 Portable Bluetooth Speaker', 'JBL', 'Audio', 129.95, 'https://m.media-amazon.com/images/I/71s46FFDCVL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Sonos Era 300 Wireless Smart Speaker White', 'Sonos', 'Audio', 449.00, 'https://m.media-amazon.com/images/I/61O3V3GXHJL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Apple Watch Ultra 2 GPS Cellular 49mm Titanium', 'Apple', 'Watch', 799.00, 'https://m.media-amazon.com/images/I/81a1zfpceVL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Samsung Galaxy Watch 6 Classic 47mm Silver', 'Samsung', 'Watch', 429.99, 'https://m.media-amazon.com/images/I/71i2XhHU3pL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Garmin Fenix 7X Pro Sapphire Solar GPS Watch', 'Garmin', 'Watch', 999.99, 'https://m.media-amazon.com/images/I/61JqiPqL1WL._AC_SL1000_.jpg', 1, NOW(), NOW()),
('TAG Heuer Connected Calibre E4 Smartwatch', 'TAG Heuer', 'Watch', 1800.00, 'https://m.media-amazon.com/images/I/71qDdlqrHML._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Sony Alpha 7 IV Full-frame Mirrorless Camera', 'Sony', 'Camera', 2498.00, 'https://m.media-amazon.com/images/I/81YH1OYVDEL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Canon EOS R6 Mark II Mirrorless Camera Body', 'Canon', 'Camera', 2499.00, 'https://m.media-amazon.com/images/I/61Ww4abGpIL._AC_SL1001_.jpg', 1, NOW(), NOW()),
('DJI Mini 4 Pro Fly More Combo Drone', 'DJI', 'Camera', 1159.00, 'https://m.media-amazon.com/images/I/61VVKqoMJaL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('GoPro HERO12 Black Action Camera Bundle', 'GoPro', 'Camera', 449.99, 'https://m.media-amazon.com/images/I/61p2fYdYQ8L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Insta360 X4 8K 360 Action Camera', 'Insta360', 'Camera', 499.99, 'https://m.media-amazon.com/images/I/61WFHjVp73L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Sony PlayStation 5 Slim Console Disc Edition', 'Sony', 'Gaming', 499.99, 'https://m.media-amazon.com/images/I/51mXM0whQtL._SL1500_.jpg', 1, NOW(), NOW()),
('Microsoft Xbox Series X 1TB Console', 'Microsoft', 'Gaming', 499.99, 'https://m.media-amazon.com/images/I/51ojzJk77qL._SL1500_.jpg', 1, NOW(), NOW()),
('Nintendo Switch OLED Model White', 'Nintendo', 'Gaming', 349.99, 'https://m.media-amazon.com/images/I/61n39btzHYL._SL1200_.jpg', 1, NOW(), NOW()),
('Steam Deck OLED 1TB Handheld Console', 'Valve', 'Gaming', 649.00, 'https://m.media-amazon.com/images/I/51BKMQy-NTL._AC_SL1191_.jpg', 1, NOW(), NOW()),
('ASUS ROG Ally 512GB Gaming Handheld', 'ASUS', 'Gaming', 599.99, 'https://m.media-amazon.com/images/I/71YeLJXT5zL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Dyson V15 Detect Absolute Cordless Vacuum', 'Dyson', 'Home', 749.99, 'https://m.media-amazon.com/images/I/61cLuhfxJjL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Nespresso Vertuo Next Coffee Machine Aeroccino', 'Nespresso', 'Home', 229.00, 'https://m.media-amazon.com/images/I/61hTavyIC0L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('KitchenAid Artisan 5-Quart Stand Mixer Empire Red', 'KitchenAid', 'Home', 449.99, 'https://m.media-amazon.com/images/I/71kJNMz8ObL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Vitamix A3500 Ascent Series Smart Blender', 'Vitamix', 'Home', 649.95, 'https://m.media-amazon.com/images/I/612qVGn3UHL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Dyson Airwrap Complete Long Styling Tool Nickel', 'Dyson', 'Home', 599.99, 'https://m.media-amazon.com/images/I/51TJGekFnPL._SL1500_.jpg', 1, NOW(), NOW()),
('iRobot Roomba j9 Self-Emptying Robot Vacuum', 'iRobot', 'Home', 899.99, 'https://m.media-amazon.com/images/I/61QWnu-lkjL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Coach Signature Canvas Shoulder Bag Khaki', 'Coach', 'Fashion', 328.00, 'https://m.media-amazon.com/images/I/718t3FsFjuL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Michael Kors Jet Set Travel Tote Brown Logo', 'Michael Kors', 'Fashion', 298.00, 'https://m.media-amazon.com/images/I/81r6TJ3e8OL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Kate Spade Spencer Saffiano Leather Crossbody', 'Kate Spade', 'Fashion', 279.00, 'https://m.media-amazon.com/images/I/61c3CQsAx1L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Tory Burch Perry Triple Compartment Tote Black', 'Tory Burch', 'Fashion', 348.00, 'https://m.media-amazon.com/images/I/71jYnzybYJL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Nike Air Jordan 1 Retro High OG Chicago', 'Nike', 'Fashion', 180.00, 'https://m.media-amazon.com/images/I/71MpGmHjJdL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Adidas Yeezy Boost 350 V2 Onyx', 'Adidas', 'Fashion', 230.00, 'https://m.media-amazon.com/images/I/714c2lPLVVL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('New Balance 990v6 Made in USA Grey', 'New Balance', 'Fashion', 199.99, 'https://m.media-amazon.com/images/I/61P9PAINeML._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Converse Chuck Taylor All Star High Top Black', 'Converse', 'Fashion', 65.00, 'https://m.media-amazon.com/images/I/81W03VTpJpL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Dyson Supersonic Hair Dryer Prussian Blue Gold', 'Dyson', 'Beauty', 429.99, 'https://m.media-amazon.com/images/I/61n7WjXgLPL._SL1500_.jpg', 1, NOW(), NOW()),
('Theragun PRO Plus Percussive Therapy Device', 'Therabody', 'Beauty', 599.00, 'https://m.media-amazon.com/images/I/61-t2R4WQWL._SL1500_.jpg', 1, NOW(), NOW()),
('NuFace Trinity Complete Facial Toning Kit', 'NuFace', 'Beauty', 395.00, 'https://m.media-amazon.com/images/I/51OmU6TmpTL._SL1500_.jpg', 1, NOW(), NOW()),
('Foreo Luna 4 Facial Cleansing Device Purple', 'Foreo', 'Beauty', 279.00, 'https://m.media-amazon.com/images/I/51rOu7YWHXL._SL1500_.jpg', 1, NOW(), NOW()),
('Peloton Bike Indoor Exercise Bike', 'Peloton', 'Sports', 2495.00, 'https://m.media-amazon.com/images/I/61s5ZzU-x7L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Theragun Elite Percussive Therapy Massager', 'Therabody', 'Sports', 399.00, 'https://m.media-amazon.com/images/I/61c4xM5upDL._SL1500_.jpg', 1, NOW(), NOW()),
('Hydrow Wave Rowing Machine with HD Screen', 'Hydrow', 'Sports', 1895.00, 'https://m.media-amazon.com/images/I/61lL-4F4jzL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Yeti Tundra 65 Hard Cooler Aquifer Blue', 'YETI', 'Sports', 375.00, 'https://m.media-amazon.com/images/I/81hMrT7FTEL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Osprey Atmos AG 65 Backpacking Backpack', 'Osprey', 'Sports', 320.00, 'https://m.media-amazon.com/images/I/81S5g0rDBjL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Amazon Echo Show 10 3rd Gen Smart Display', 'Amazon', 'Smart Home', 249.99, 'https://m.media-amazon.com/images/I/61Bj64GNKZL._AC_SL1000_.jpg', 1, NOW(), NOW()),
('Google Nest Learning Thermostat 4th Gen', 'Google', 'Smart Home', 279.99, 'https://m.media-amazon.com/images/I/51yfCN8nk-L._AC_SL1000_.jpg', 1, NOW(), NOW()),
('Ring Video Doorbell Pro 2 with 3D Motion', 'Ring', 'Smart Home', 249.99, 'https://m.media-amazon.com/images/I/51Xg3C0JSSL._SL1000_.jpg', 1, NOW(), NOW()),
('Philips Hue White and Color Ambiance Starter Kit', 'Philips', 'Smart Home', 199.99, 'https://m.media-amazon.com/images/I/612lKB0JcVL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Arlo Pro 5S 2K Spotlight Camera 3-Pack', 'Arlo', 'Smart Home', 549.99, 'https://m.media-amazon.com/images/I/51xp0HQSZ2L._SL1500_.jpg', 1, NOW(), NOW()),
('Apple Studio Display 27 5K Retina', 'Apple', 'Computer', 1599.00, 'https://m.media-amazon.com/images/I/71f1AwJj0YL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('LG UltraGear 27 4K 144Hz Gaming Monitor', 'LG', 'Computer', 799.99, 'https://m.media-amazon.com/images/I/81JhGNqFkKL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Logitech MX Master 3S Wireless Mouse', 'Logitech', 'Computer', 99.99, 'https://m.media-amazon.com/images/I/61ni3t1ryQL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Apple Magic Keyboard with Touch ID and Numeric', 'Apple', 'Computer', 199.00, 'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Samsung 990 Pro 2TB NVMe M2 SSD', 'Samsung', 'Computer', 179.99, 'https://m.media-amazon.com/images/I/51GfyZKjJuL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('LG C3 65 OLED evo 4K Smart TV', 'LG', 'TV', 1496.99, 'https://m.media-amazon.com/images/I/91F9JWQK4TL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Samsung 75 Neo QLED 8K Smart TV QN900C', 'Samsung', 'TV', 4997.99, 'https://m.media-amazon.com/images/I/71RFPsPC9hL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Sony 65 Bravia XR A95L QD-OLED 4K Google TV', 'Sony', 'TV', 2798.00, 'https://m.media-amazon.com/images/I/91Vb7Nfs5lL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Sonos Arc Premium Smart Soundbar Black', 'Sonos', 'TV', 899.00, 'https://m.media-amazon.com/images/I/71tyxZ5FVOL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Bose Smart Soundbar 900 with Dolby Atmos', 'Bose', 'TV', 899.00, 'https://m.media-amazon.com/images/I/71-9yFHdE8L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Montblanc Meisterstuck Platinum Fountain Pen', 'Montblanc', 'Luxury', 630.00, 'https://m.media-amazon.com/images/I/61WtplUq4kL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Ray-Ban Aviator Classic Gold Green G-15', 'Ray-Ban', 'Luxury', 163.00, 'https://m.media-amazon.com/images/I/51g6OLCVPvL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Oakley Sutro Prizm Road Cycling Sunglasses', 'Oakley', 'Luxury', 194.00, 'https://m.media-amazon.com/images/I/61hCvw00vRL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Persol Steve McQueen Special Edition Sunglasses', 'Persol', 'Luxury', 450.00, 'https://m.media-amazon.com/images/I/51TZzVdFN8L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Tumi Alpha 3 Continental Expandable Carry-On', 'Tumi', 'Luxury', 895.00, 'https://m.media-amazon.com/images/I/81Y8Z3OwvdL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Rimowa Original Cabin Aluminum Suitcase Silver', 'Rimowa', 'Luxury', 1200.00, 'https://m.media-amazon.com/images/I/61m0rMhePaL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Herman Miller Aeron Chair Graphite Size C', 'Herman Miller', 'Office', 1395.00, 'https://m.media-amazon.com/images/I/41uueqMbuBL._AC_SL1024_.jpg', 1, NOW(), NOW()),
('Steelcase Leap V2 Ergonomic Office Chair', 'Steelcase', 'Office', 1239.00, 'https://m.media-amazon.com/images/I/71Hf7tEDJVL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Uplift V2 Standing Desk 60x30 Walnut Top', 'Uplift', 'Office', 799.00, 'https://m.media-amazon.com/images/I/71hIYGRmMFL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('CalDigit TS4 Thunderbolt 4 Dock 18 Ports', 'CalDigit', 'Office', 399.99, 'https://m.media-amazon.com/images/I/61O3qqBxqYL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Yamaha P-125 88-Key Digital Piano Black', 'Yamaha', 'Music', 699.99, 'https://m.media-amazon.com/images/I/71L3UlG4MAL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Fender Player Stratocaster Electric Guitar', 'Fender', 'Music', 849.99, 'https://m.media-amazon.com/images/I/61vHiZrSEaL._AC_SL1200_.jpg', 1, NOW(), NOW()),
('Audio-Technica AT2020 Cardioid Condenser Mic', 'Audio-Technica', 'Music', 99.00, 'https://m.media-amazon.com/images/I/71SZ9AVCDBL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Shure SM7B Dynamic Vocal Microphone', 'Shure', 'Music', 399.00, 'https://m.media-amazon.com/images/I/81Y5pB-vkgL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Roland TD-17KVX V-Drums Electronic Drum Kit', 'Roland', 'Music', 2299.99, 'https://m.media-amazon.com/images/I/71n0YXnHt8L._AC_SL1500_.jpg', 1, NOW(), NOW()),
('UPPAbaby Vista V2 Stroller Greyson', 'UPPAbaby', 'Baby', 1099.99, 'https://m.media-amazon.com/images/I/71pPOL-O2dL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Bugaboo Fox 5 Complete Stroller Black', 'Bugaboo', 'Baby', 1499.00, 'https://m.media-amazon.com/images/I/61MU1dpCBYL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('LEGO Star Wars Millennium Falcon 75375', 'LEGO', 'Baby', 84.99, 'https://m.media-amazon.com/images/I/81K91uuuFtL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Nintendo Switch Lite Turquoise', 'Nintendo', 'Baby', 199.00, 'https://m.media-amazon.com/images/I/61fSLBf8VnL._SL1500_.jpg', 1, NOW(), NOW()),
('Furbo 360 Dog Camera Treat Tossing Full HD', 'Furbo', 'Pet', 210.00, 'https://m.media-amazon.com/images/I/51eTiUoA7oL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('PetSafe ScoopFree Self-Cleaning Litter Box', 'PetSafe', 'Pet', 169.95, 'https://m.media-amazon.com/images/I/71MckjhmtSL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('PETKIT PURA X Self-Cleaning Cat Litter Box', 'PETKIT', 'Pet', 549.00, 'https://m.media-amazon.com/images/I/51KBXQ5CPXL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Oura Ring Gen 3 Heritage Silver Size 10', 'Oura', 'Health', 299.00, 'https://m.media-amazon.com/images/I/51etWL5C0gL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Withings Body Smart Wi-Fi Scale Black', 'Withings', 'Health', 99.95, 'https://m.media-amazon.com/images/I/71xZ3VtbloL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Theragun Mini 2.0 Portable Massager', 'Therabody', 'Health', 199.00, 'https://m.media-amazon.com/images/I/614zwEdDvmL._SL1500_.jpg', 1, NOW(), NOW()),
('Whoop 4.0 Health Fitness Tracker Onyx', 'Whoop', 'Health', 239.00, 'https://m.media-amazon.com/images/I/41TbBJdHKnL._AC_SL1200_.jpg', 1, NOW(), NOW()),
('Thinkware U1000 4K Dash Cam Front and Rear', 'Thinkware', 'Auto', 499.99, 'https://m.media-amazon.com/images/I/61mRAPfH2gL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('Blackvue DR900X-2CH Plus 4K Dash Camera', 'Blackvue', 'Auto', 519.99, 'https://m.media-amazon.com/images/I/61fLfI7hVNL._AC_SL1500_.jpg', 1, NOW(), NOW()),
('NOCO Boost X GBX155 4250A Jump Starter', 'NOCO', 'Auto', 349.95, 'https://m.media-amazon.com/images/I/71y3DfFUgpL._AC_SL1500_.jpg', 1, NOW(), NOW());
